filter:
    # fails when this is missing
    paths: ["src/*", "tests/*"]

tools:
    # enabled code coverage provided by tester (x of 100 %)
    external_code_coverage: true

checks:
    php:
        code_rating: true
        duplication: true
