language: php

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

php:
    - 7.0

install:
    - composer install --no-interaction --prefer-source

script:
    - php vendor/bin/phpstan analyse ./src ./tests --level 5
    - php vendor/bin/phpcs --standard=vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PSR2/ruleset.xml ./src ./tests
    - php vendor/bin/tester tests -p phpdbg --coverage ./coverage.xml --coverage-src ./src

after_script:
    # upload coverage.xml file to Scrutinizer to analyze it
    - >
      wget https://scrutinizer-ci.com/ocular.phar &&
      php ocular.phar code-coverage:upload --format=php-clover coverage.xml
