language: php

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.0
    - 7.1
    - 7.2

env:
    - KDYBY_DOCTRINE_VERSION="~3.1"
    - KDYBY_DOCTRINE_VERSION="4.0.*@dev"

install:
    - composer install --no-interaction --prefer-source
    - composer require kdyby/doctrine:${KDYBY_DOCTRINE_VERSION} --dev --no-interaction --prefer-source

script:
    - php vendor/bin/phpstan analyse ./src ./tests --level 7
    - php vendor/bin/phpcs --standard=PSR2 ./src ./tests
    - php vendor/bin/tester tests -p phpdbg --coverage ./coverage.xml --coverage-src ./src

after_script:
    # Report Code Coverage
    - >
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      && php coveralls.phar --verbose --config .coveralls.yml